### ISSUE TITLE
command line interface

### ISSUE THREAD

**Issue by fommil** [Yuki-Inoue/elisp-format#1]
I have started work on a command line interface to `elisp-format` based on the same pattern used by `ert-runner`. Would you be interested in taking my fixes to the recursive directory scanner? And potentially the executable bits too (or I can continue to depend on your package) https://gitlab.com/fommil/elisp-fmt

**Comment by Yuki-Inoue** [comment]
OMG... I've totally didn't notice this... Terribly sorry.  Will look into it.

**Comment by fommil** [comment]
I never got my cli to work, but I'd love to return to it at some point.

**Comment by Yuki-Inoue** [comment]
I'm not familiar with ert-runner, but I understood that its interface allows some kind of pattern for designating dirs/files.  Yes, integrating it would be pretty natural enhancement to this package, it would be welcome.

**Comment by Yuki-Inoue** [comment]
About the cask related things, including it in this repository, I feel a bit awkward..  I created this repository in order to make it available on package manager e.g. melpa or el-get.  I assume supporting for cask adds a bit of complexity,, and at most, I've never used cask so I don't think I can maintain a good cask package..
